name: Upload ahnf to pypi

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools setuptools_scm[toml] wheel twine build
    - name: Build, publish to test server, check package installation
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.ABNF_TEST_PYPI_PASSWORD }}
      run: |
        python -m build
        twine upload upload --repository testpypi dist/*
        python -m venv test
        pip install --index-url https://test.pypi.org/simple/ --no-deps abnf-declaresub
        python -c "import abnf"
